import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bechoo | An exclusive resale platform for NITS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span style={{ color: "#FB2576" }}>Bechoo.shop!</span>
        </h1>
        <h2>An <span style={{ color: "maroon" }}>exclusive</span> resale platform for <span style={{ color: "maroon" }}>NITS</span></h2>
        <br />
        <h3>Made with ❤️ by <a style={{ color: "blue" }} href='https://www.linkedin.com/in/gauravdas014/' target="_blank" >Gaurav</a></h3>
      </main >
    </div >
  )
}
